// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package go_micro_srv_message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           string   `protobuf:"bytes,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Message) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Message) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type MessageListResponse struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Messages             []*Message `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Page                 *PageMap   `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageListResponse) Reset()         { *m = MessageListResponse{} }
func (m *MessageListResponse) String() string { return proto.CompactTextString(m) }
func (*MessageListResponse) ProtoMessage()    {}
func (*MessageListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageListResponse.Unmarshal(m, b)
}
func (m *MessageListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageListResponse.Marshal(b, m, deterministic)
}
func (m *MessageListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageListResponse.Merge(m, src)
}
func (m *MessageListResponse) XXX_Size() int {
	return xxx_messageInfo_MessageListResponse.Size(m)
}
func (m *MessageListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageListResponse proto.InternalMessageInfo

func (m *MessageListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MessageListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *MessageListResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *MessageListResponse) GetPage() *PageMap {
	if m != nil {
		return m.Page
	}
	return nil
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type IdResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id                   uint32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdResponse) Reset()         { *m = IdResponse{} }
func (m *IdResponse) String() string { return proto.CompactTextString(m) }
func (*IdResponse) ProtoMessage()    {}
func (*IdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *IdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdResponse.Unmarshal(m, b)
}
func (m *IdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdResponse.Marshal(b, m, deterministic)
}
func (m *IdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdResponse.Merge(m, src)
}
func (m *IdResponse) XXX_Size() int {
	return xxx_messageInfo_IdResponse.Size(m)
}
func (m *IdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdResponse proto.InternalMessageInfo

func (m *IdResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *IdResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *IdResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PageNumPageSize struct {
	PageNum              int32    `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageNumPageSize) Reset()         { *m = PageNumPageSize{} }
func (m *PageNumPageSize) String() string { return proto.CompactTextString(m) }
func (*PageNumPageSize) ProtoMessage()    {}
func (*PageNumPageSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *PageNumPageSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageNumPageSize.Unmarshal(m, b)
}
func (m *PageNumPageSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageNumPageSize.Marshal(b, m, deterministic)
}
func (m *PageNumPageSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageNumPageSize.Merge(m, src)
}
func (m *PageNumPageSize) XXX_Size() int {
	return xxx_messageInfo_PageNumPageSize.Size(m)
}
func (m *PageNumPageSize) XXX_DiscardUnknown() {
	xxx_messageInfo_PageNumPageSize.DiscardUnknown(m)
}

var xxx_messageInfo_PageNumPageSize proto.InternalMessageInfo

func (m *PageNumPageSize) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *PageNumPageSize) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type PageMap struct {
	PageNum              int32    `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageMap) Reset()         { *m = PageMap{} }
func (m *PageMap) String() string { return proto.CompactTextString(m) }
func (*PageMap) ProtoMessage()    {}
func (*PageMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *PageMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageMap.Unmarshal(m, b)
}
func (m *PageMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageMap.Marshal(b, m, deterministic)
}
func (m *PageMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageMap.Merge(m, src)
}
func (m *PageMap) XXX_Size() int {
	return xxx_messageInfo_PageMap.Size(m)
}
func (m *PageMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PageMap.DiscardUnknown(m)
}

var xxx_messageInfo_PageMap proto.InternalMessageInfo

func (m *PageMap) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *PageMap) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageMap) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.message.Message")
	proto.RegisterType((*MessageListResponse)(nil), "go.micro.srv.message.MessageListResponse")
	proto.RegisterType((*Response)(nil), "go.micro.srv.message.Response")
	proto.RegisterType((*IdResponse)(nil), "go.micro.srv.message.IdResponse")
	proto.RegisterType((*PageNumPageSize)(nil), "go.micro.srv.message.PageNumPageSize")
	proto.RegisterType((*PageMap)(nil), "go.micro.srv.message.PageMap")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xd2, 0x34, 0x4d, 0x3b, 0x1f, 0xad, 0x32, 0x16, 0x09, 0x05, 0x25, 0x2c, 0x08, 0xf5,
	0x12, 0xb4, 0x9e, 0xbc, 0x7a, 0x29, 0x05, 0x2b, 0xb2, 0xd5, 0xa3, 0x87, 0x98, 0x0c, 0x61, 0x0f,
	0xe9, 0x2e, 0xd9, 0xa4, 0xa0, 0x7f, 0xc1, 0x5f, 0xe2, 0xbf, 0x94, 0x6c, 0x36, 0xb5, 0x07, 0x2b,
	0xd4, 0x53, 0xe6, 0xcd, 0x9b, 0x9d, 0xbc, 0xb7, 0x6f, 0x61, 0x98, 0x93, 0xd6, 0x71, 0x46, 0x91,
	0x2a, 0x64, 0x29, 0x71, 0x9c, 0xc9, 0x28, 0x17, 0x49, 0x21, 0x23, 0x5d, 0x6c, 0x22, 0xcb, 0xb1,
	0x0f, 0x07, 0xfc, 0x65, 0x53, 0xe3, 0x08, 0x3a, 0x22, 0x0d, 0x9c, 0xd0, 0x99, 0x0e, 0x79, 0x47,
	0xa4, 0x78, 0x0a, 0xbd, 0x4a, 0x53, 0xb1, 0x48, 0x83, 0x8e, 0xe9, 0x59, 0x84, 0x01, 0xf8, 0xf6,
	0x78, 0xe0, 0x86, 0xce, 0x74, 0xc0, 0x5b, 0x88, 0xe7, 0x00, 0x49, 0x41, 0x71, 0x49, 0x4f, 0x22,
	0xa7, 0xc0, 0x33, 0xe4, 0x4e, 0xa7, 0xe6, 0x2b, 0x95, 0xb6, 0x7c, 0xaf, 0xe1, 0xbf, 0x3b, 0xec,
	0xd3, 0x81, 0x13, 0xab, 0xe6, 0x5e, 0xe8, 0x92, 0x93, 0x56, 0x72, 0xad, 0x09, 0x11, 0xba, 0x89,
	0x4c, 0xc9, 0x68, 0xf3, 0xb8, 0xa9, 0xf1, 0x18, 0xdc, 0x5c, 0x67, 0x46, 0xda, 0x80, 0xd7, 0x25,
	0xde, 0x42, 0xdf, 0x0a, 0xd1, 0x81, 0x1b, 0xba, 0xd3, 0xff, 0xb3, 0xb3, 0xe8, 0x27, 0xd3, 0x91,
	0xfd, 0x05, 0xdf, 0x8e, 0xe3, 0x35, 0x74, 0x55, 0xed, 0xa7, 0x1b, 0x3a, 0xfb, 0x8f, 0x3d, 0xc6,
	0x19, 0x2d, 0x63, 0xc5, 0xcd, 0x28, 0xbb, 0x82, 0xfe, 0x61, 0xfa, 0xd8, 0x1d, 0xc0, 0x22, 0x3d,
	0xd0, 0x53, 0x93, 0x89, 0xdb, 0x66, 0xc2, 0xe6, 0x70, 0x54, 0xcb, 0x78, 0xa8, 0xf2, 0xfa, 0xb3,
	0x12, 0xef, 0x54, 0xc7, 0xa1, 0x9a, 0x96, 0xdd, 0xd5, 0x42, 0x9c, 0x40, 0x5f, 0xd9, 0x29, 0xb3,
	0xd3, 0xe3, 0x5b, 0xcc, 0x9e, 0xc1, 0xb7, 0x7e, 0xfe, 0xb6, 0x00, 0xc7, 0xe0, 0x25, 0xb2, 0x5a,
	0x97, 0x46, 0x9c, 0xc7, 0x1b, 0x30, 0x93, 0x30, 0xb2, 0xb7, 0xbb, 0xa2, 0x62, 0x23, 0x12, 0xc2,
	0x17, 0xf0, 0xe7, 0x54, 0x2e, 0xe3, 0xf5, 0x1b, 0x5e, 0xec, 0xbf, 0xd7, 0x1d, 0x43, 0x93, 0xcb,
	0x5f, 0x53, 0xdb, 0x7d, 0x18, 0xec, 0xdf, 0x6b, 0xcf, 0xbc, 0xee, 0x9b, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x36, 0xac, 0xe1, 0xe7, 0xee, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MessageService service

type MessageServiceClient interface {
	//    rpc Create (User) returns (Response) {
	//    }
	//    rpc GetOne (UserId) returns (UserResponse) {
	//    }
	GetMany(ctx context.Context, in *PageNumPageSize, opts ...client.CallOption) (*MessageListResponse, error)
}

type messageServiceClient struct {
	c           client.Client
	serviceName string
}

func NewMessageServiceClient(serviceName string, c client.Client) MessageServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.message"
	}
	return &messageServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *messageServiceClient) GetMany(ctx context.Context, in *PageNumPageSize, opts ...client.CallOption) (*MessageListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "MessageService.GetMany", in)
	out := new(MessageListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MessageService service

type MessageServiceHandler interface {
	//    rpc Create (User) returns (Response) {
	//    }
	//    rpc GetOne (UserId) returns (UserResponse) {
	//    }
	GetMany(context.Context, *PageNumPageSize, *MessageListResponse) error
}

func RegisterMessageServiceHandler(s server.Server, hdlr MessageServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&MessageService{hdlr}, opts...))
}

type MessageService struct {
	MessageServiceHandler
}

func (h *MessageService) GetMany(ctx context.Context, in *PageNumPageSize, out *MessageListResponse) error {
	return h.MessageServiceHandler.GetMany(ctx, in, out)
}
