all:
# 	protoc -IC:\MyInstall\code\gomicrodemo1\src\article-service\proto\article --go_out=plugins=micro:C:\MyInstall\code\gomicrodemo1\src\article-service\proto\article C:\MyInstall\code\gomicrodemo1\src\article-service\proto\article\article.proto
# 	protoc -I. --go_out=plugins=micro:. *.proto
# 	protoc --proto_path=.:. --micro_out=. --go_out=. article.proto
	protoc --proto_path=.:. --micro_out=../pb --go_out=../pb *.proto
